# Generated by Django 4.1 on 2022-11-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gac_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=50)),
                ('gac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gac.gac')),
            ],
        ),
    ]
