# Generated by Django 4.1 on 2022-11-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gac',
            old_name='gac_name',
            new_name='gac_text',
        ),
        migrations.RenameField(
            model_name='produceraffiliation',
            old_name='producer_name',
            new_name='producer_text',
        ),
    ]
