# Generated by Django 4.1 on 2022-11-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gac', '0002_rename_gac_name_gac_gac_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='produceraffiliation',
            name='gac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gac.marketplace'),
        ),
        migrations.DeleteModel(
            name='GAC',
        ),
    ]
