# Generated by Django 4.1 on 2022-11-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gac', '0004_remove_produceraffiliation_gac'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceraffiliation',
            name='gac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gac.marketplace'),
        ),
    ]
