# Generated by Django 4.1 on 2022-11-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gac', '0006_product_delete_produceraffiliation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_list_users', 'Can list users'),)},
        ),
    ]
