# Generated by Django 4.1 on 2022-11-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gac', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
